# 환경변수 기반 설정 파일
# 운영 환경에서 사용할 환경 변수들 정의

# 데이터베이스 연결 정보
DB_URL: jdbc:postgresql://localhost:5432/postgres
DB_USERNAME: postgres
DB_PASSWORD: password

# 서버 설정
SERVER_PORT: 8080

# 로깅 레벨
LOG_LEVEL: INFO

# NCP 관련 설정 (향후 확장용)
NCP_ACCESS_KEY: 
NCP_SECRET_KEY: 
NCP_REGION: kr-standard

# 비용 계산 상수 (필요시 환경변수로 오버라이드)
COST_CPU_CORE_HOUR: 0.05
COST_IO_OPERATION: 0.0001
COST_MEMORY_GB_HOUR: 0.01
COST_NETWORK_TRANSFER_GB: 0.09
